### ISSUE TITLE
Fails on importing Client. Python 3.7.1

### ISSUE THREAD

**Issue by erezlevanon** [mhadam/clutch#13]
Version: 2.0.3
Python version: 3.7.1
OS: Windows 10

After installing with

`pip install transmission-clutch`

running

`from clutch.client import Client`

fails with

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\clutch\client.py", line 1, in <module>
    from clutch.method.group.queue import QueueMethods
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\clutch\method\group\queue.py", line 6, in <module>
    from clutch.method.group.method import MethodNamespace
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\clutch\method\group\method.py", line 4, in <module>
    from clutch.network.connection import Connection
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\clutch\network\connection.py", line 6, in <module>
    from clutch.network.rpc.message import Response, Request
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\clutch\network\rpc\message.py", line 2, in <module>
    from typing import TypedDict, Mapping, Any, TypeVar, Generic
ImportError: cannot import name 'TypedDict' from 'typing' (C:\Program Files (x86)\Python37-32\lib\typing.py)`

**Comment by mhadam** [comment]
Hi @erezlevanon ,
At the moment, you can solve this by using Python 3.8. I need to update the project to specify that it's only 3.8 compatible right now. Otherwise you can use the legacy version of the library (transmission-clutch==1.0.6).

That being said, I'll make the effort to offer greater compatibility for all Python 3 releases. But at the moment, clutch is leveraging new features(TypedDict, dataclass, etc.) that help to check against the RPC spec, and I have to make changes that accommodate the different versions.

Thanks for reporting this!

**Comment by erezlevanon** [comment]
Thanks for the quick response @mhadam!

**Comment by mhadam** [comment]
Hi @erezlevanon,
I'm finishing up a new release that fixes 3.7 compatibility (so far it works in my testing, but it'd be a great help if you can verify).

The API is changed though - I'm using pydantic now, so methods return a class from pydantic that's similar to `dataclass`. There's some useful methods on the response object like `dict()` and `json()` and it's worth mentioning they have (among others) an `exclude_none` keyword.

For example:
```
client.session.accessor().dict(exclude_none=True)
```
